### ISSUE TITLE
Fix discovery merging

### ISSUE THREAD

**Issue by psFried** [estuary/flow#1285]
Discussed in #1268 

- [x] Update the Spec response to add a resource_path_pointers field (#1291)
- [x] Have agent use the resource_path_pointers, if available, to extract a resource_path for each binding, which is used as an identity to merge the bindings (also #1291)
- [x] Update sql batch connectors to set resource_path_pointers in the spec response (estuary/connectors#1083)
- [x] Update other connectors to set resource_path_pointers in the spec response (estuary/airbyte#284 and estuary/connectors#1083)
- [ ] Update agent to require that `resource_path_pointers` always be set

Follow up items from [this discussion](https://github.com/estuary/flow/pull/1291#discussion_r1401022269):

- [ ] Deprecate `resource_path` in Validated response, and add it to Validate request instead
    - [ ] This requires threading through the connector spec as part of validation
- [ ] If Validated response does include `resource_path`, validate that it matches the computed one
- [ ] The `connector_tags` handler should validate that `resource_path_pointers` must not be changed after they're initially set
