### ISSUE TITLE
inferred schema updates blocking interactive publications of captures and materializations

### ISSUE THREAD

**Issue by psFried** [estuary/flow#1520]
Say you have a capture and materialization with many bindings that use inferred schemas. When the control plane publishes the inferred schemas, it increases the `last_pub_id` of the collection. If a user goes into the UI to try to publish the capture or materialization, the collection gets added to the `LiveCatalog` with a `last_pub_id` that is potentially greater than the `id` of the current publication. This results in [this error being returned](https://github.com/estuary/flow/blob/8f5145eb5742328bfffc1bbbc82535735ce1180c/crates/validation/src/lib.rs#L211).

## Current plan (updated after discussion)

- [x] (#1623) Switch to using `last_build_id` instead of `last_pub_id` for optimistic locking
- [x] (#1623) Introduce the concept of a "touch" publication, which only updates the `built_spec`, leaving the `spec` and `last_pub_id` unchanged
- [x] (#1623) Controllers will hash the `last_pub_id`s of all their dependencies in order to determine whether they need to do a touch publication to update their own `built_spec`.
    - This prevents the `last_pub_id` from being incremented when the dependencies of a spec have changed, thus avoiding `ExpectPubIdNotMatched` errors caused by that.
- [ ] (PR tbd) Update the publications handler to always inject the current inferred schema into the models of drafted (non-touch) collections.
    - This allows the UI and `flowctl` to stop setting `expectPubId` on collection specs. They must set it currently to avoid clobbering inferred schema changes, but this will make clobbering inferred schemas impossible, so `expectPubId` will no longer be needed.
- [ ] (PR tbd) Update the UI to no longer set `expectPubId` for collection specs when editing captures.
    - It must still set it for the capture specs, though.
    - This avoids the possibility for `expectPubId` conflicts on the collections
- [ ] (PR tbd) Update the publications handler to generate a new `pub_id` for each publication instead of using the `id` of the `publications` row, and to retry `PublicationSuperseded` errors
    - Inventing a new `pub_id` is what allows us to retry these errors by generating a new (higher) `pub_id`

**Comment by dyaffe** [comment]
FYI I'm having a ton of trouble with this now.  It is happening for SaaS connectors that use schema inference, even if they have few bindings as well and preventing publication.

**Comment by psFried** [comment]
@jgraettinger I'm starting to wonder if perhaps [this check](https://github.com/estuary/flow/blob/8f5145eb5742328bfffc1bbbc82535735ce1180c/crates/validation/src/lib.rs#L211) should simply be removed, and allow an expanded live spec to have a publication id that's greater than the current publication id.

My read of this is that it's not necessarily _incorrect_ for a live spec to have a larger publication id, and that the check exists as a way of detecting the case where a change to a related live spec could not possibly have been observed prior to creating the publication that depends on it. If that's right, then I'm thinking it might be a bit too restrictive. Is there some other reason for this check to exist?

Removing that check might help, especially for materializations. For captures, interactive publications tend to include the collection specs, too. So it seems possible that removing the check above would be insufficient to unblock interactive publications, since it might just result in either an `expectPubId` mismatch or collection changes being overwritten. We do at least try to prune unchanged collection specs from the draft, though, so it's also possible that may reduce the likelihood of running into an `expectPubId` mismatch.

I'm still reading and thinking through how best to solve this one, but curious if you have any thoughts.

**Comment by psFried** [comment]
The essense of this issue is about how we handle concurrent publications of live specs. In the case we're looking at now, the publications are coming from a user and from background controllers. But this could also happen with two or more users just using the UI or flowctl. To be fair, we're talking about concurrent edits to complex nested specifications, which just isn't really a _solved_ problem in the general sense. So there probably isn't a general solution that can guarantee that conflicts will never occur. Instead, we can try to:

- Minimize the liklihood of conflicts occurring in the first place
- Build UX around resolving conflicts when they do occur
- Try to be more tolerant of edits that clobber the inferred schema

Here's some ideas to get the ball rolling:

We could try introducing a way to temporarily defer background controllers while users are editing in the UI. This doesn't help with flowctl, or with conflicts arising from concurrent edits from multiple users. It might still be a reasonable thing to do at some point, but it's non-trivial work to build and maintain, so I'm not _super_ keen on this one at this point. But a basic sketch could be something like an `editing_sessions` table where rows mark individual specs as being edited for some limited duration (which the UI can extend). We'd essentially have controllers skip publishing something if it's being edited.

Remove the `PublicationSuperseded` error. Still not 100% sure, but it seems like we technically _could_.

Automate retrying on `PublicationSuperceded` errors with a new publication id. This would need to be implemented in the UI and flowctl, since it would need to be a new publication, not just retrying with the existing publication id.

Regardless of what we do to work around `PublicationSuperseded` errors, we might still run into problems with `ExpectPubIdNotMatched`. The `expect_pub_id` is set when you do a discover, so if there's an inferred schema update after you hit the "refresh" button in the UI and before you "Save and publish", then your publication would still fail. In this case, you couldn't just retry, since the `expect_pub_id` on your draft specs will still be outdated. You'd need to do something to update the `expect_pub_id` to the current value, and we'd need to build UX around that.

Retrying on `ExpectPubIdNotMatched` can be a pain because the live spec itself may have had changes that are not reflected in the current draft. In the general case, there's no easy way to solve this automatically. For example, the live spec could have had a binding added, and then if you try to re-play your drafted changes on top of the new live spec, the binding indexes may no longer align. But we could handle the special, but common case where the live spec hasn't actually changed. If it hasn't changed, then we can just update `expect_pub_id` and re-try the publication.

Another possible mitigation would be to limit how frequently controllers would publish their specs in response to changes in their dependencies. We could have them publish at most every 10 minutes, scheduling for a future time if there's been a publication more recently. The main benefit of this approach is just that it's easy to implement. It seems like in practice we'd need at least a 10-15 minute interval in between publishes if we wanted to allow enough time for users to go though the whole discover/publish workflow, which would increase the time it takes to propagate inferred schema changes. And there's still of course the possiblity that the once-every-15-minutes update happens to go though right when you're in the middle of something in the UI. And in many cases, the materialization would not be able to make progress until this publication goes through. Even with those limitations, there's maybe still something nice about the idea of "materializations will only apply schema changes at most every X minutes".
