### ISSUE TITLE
control: Scaffolding

### ISSUE THREAD

**Issue by saterus** [estuary/flow#339]
We need to get a few things in place before there's much ability to make real progress on the Control Plane.

## TODO:
- [x] `cargo new control`
- [x] Add `/health_check` endpoint
- [x] Add precanned `/connectors` endpoint
- [x] Add simple tests
- [x] Dockerfile
- [x] Run tests in CI workflow
- [x] Environmental configuration mechanism
