### ISSUE TITLE
Allowing inbound TCP connections to connector containers

### ISSUE THREAD

**Issue by psFried** [estuary/flow#868]
### Discussed in https://github.com/estuary/flow/discussions/840

The high-level goal is to allow inbound networking for containers that we run on our platform.
This issue description will be kept up to date with the overall status. Let's use the discussion for resolving additional questions and feedback as it comes up.

### Status: Merged!

**PRs:**

- flow: estuary/flow#893
- data-plane-gateway: estuary/data-plane-gateway#27
- connectors: estuary/connectors#565

### TODO

- [x] Add tests for gRPC proxy services
- [ ] ~~Introduce `flowctl port-forward` subcommand to support protocols such as postgres, which do not use ALPN~~
- [ ] ~~Finish updating `ops/*/stats` collections to include networking stats, and publish stats as part of proxying~~
- [x] Update CertManager in the data-plane to allow using `dns-01` acme challenges, and provision a wildcard certificate for `*.combustible-cronut.estuary-data.dev`
- [x] Add the new data-plane-gateway deployment to combustible-cronut
- [x] Introduce a `source-http-ingest` connector that publishes data from HTTP requests

**Comment by psFried** [comment]
This is now complete. There's still one related oustanding issue (estuary/data-plane-gateway#30), but the basic features are all present and working, so I'm closing this issue.
